### ISSUE TITLE
Comment

### ISSUE THREAD

**Issue by dmadrigalejos** [Jas1028/Assignment5#1]
https://github.com/Jas1028/Assignment5/blob/dd551f0b4babeeb2c4f7bc3dcfd67c2bff0cc72c/Program_1_Grade_Percentage.py#L24

Kaylangan mong i round-off in input pag may decimal point. Try mo 96.6 mali output.

**Comment by Jas1028** [comment]
Sir, I fixed na po. Thank you po sir.

**Comment by Jas1028** [comment]
> 
Sir, I fixed na po. Thank you po
